/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Inspiration = {
  _id: string;
  _type: "inspiration";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  video?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    _type: "file";
  };
  mediaType: "image" | "video";
  title?: string;
  publishedAt: string;
};

export type ReadingLog = {
  _id: string;
  _type: "readingLog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  publishedAt: string;
  title?: string;
  author?: string;
  slug?: Slug;
  memo?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type Poem = {
  _id: string;
  _type: "poem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  year?: "2020" | "2021" | "2022" | "2023" | "2024" | "2025" | "2026" | "2027" | "2028" | "2029" | "2030";
  publishedAt: string;
  slug: Slug;
  body?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    _type: "file";
    _key: string;
  }>;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type PoetOfTheMonth = {
  _id: string;
  _type: "poetOfTheMonth";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  poet: string;
  month?: string;
  slug: Slug;
  publishedAt: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type MiscProse = {
  _id: string;
  _type: "miscProse";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  tag?: string;
  sumarry?: string;
  slug: Slug;
  publishedAt: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Haiku = {
  _id: string;
  _type: "haiku";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  publishedAt: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | Geopoint | Inspiration | ReadingLog | Poem | SanityFileAsset | PoetOfTheMonth | MiscProse | Slug | SanityImageCrop | SanityImageHotspot | SanityImageAsset | SanityAssetSourceData | SanityImageMetadata | Haiku;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/queries/haiku.ts
// Variable: listHaiku
// Query: *[_type == "haiku"] | order(date desc)
export type ListHaikuResult = Array<{
  _id: string;
  _type: "haiku";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  publishedAt: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
}>;

// Source: ./sanity/queries/inspiration.ts
// Variable: listInspirations
// Query: *[_type == "inspiration"] | order(publishedAt desc)
export type ListInspirationsResult = Array<{
  _id: string;
  _type: "inspiration";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  video?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    _type: "file";
  };
  mediaType: "image" | "video";
  title?: string;
  publishedAt: string;
}>;

// Source: ./sanity/queries/miscProse.ts
// Variable: listMiscProse
// Query: *[_type == "miscProse"] | order(date desc)
export type ListMiscProseResult = Array<{
  _id: string;
  _type: "miscProse";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  tag?: string;
  sumarry?: string;
  slug: Slug;
  publishedAt: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
}>;
// Variable: getMiscProseBySlug
// Query: *[_type == "miscProse" && slug.current == $slug][0]
export type GetMiscProseBySlugResult = {
  _id: string;
  _type: "miscProse";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  tag?: string;
  sumarry?: string;
  slug: Slug;
  publishedAt: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
} | null;
// Variable: listMiscProseSlug
// Query: *[_type == "miscProse"] {        "slug": slug.current    }
export type ListMiscProseSlugResult = Array<{
  slug: string;
}>;

// Source: ./sanity/queries/poetOfTheMonth.ts
// Variable: listPoetOfTheMonth
// Query: *[_type == "poetOfTheMonth"] | order(publishedAt desc)
export type ListPoetOfTheMonthResult = Array<{
  _id: string;
  _type: "poetOfTheMonth";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  poet: string;
  month?: string;
  slug: Slug;
  publishedAt: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
}>;
// Variable: getPoetOfTheMonthBySlug
// Query: *[_type == "poetOfTheMonth" && slug.current == $slug][0]
export type GetPoetOfTheMonthBySlugResult = {
  _id: string;
  _type: "poetOfTheMonth";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  poet: string;
  month?: string;
  slug: Slug;
  publishedAt: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
} | null;
// Variable: listPoetOfTheMonthSlug
// Query: *[_type == "poetOfTheMonth"] {        "slug": slug.current    }
export type ListPoetOfTheMonthSlugResult = Array<{
  slug: string;
}>;

// Source: ./sanity/queries/poetry.ts
// Variable: listPoetry
// Query: *[_type == "poetry"] | order(publishedAt desc)
export type ListPoetryResult = Array<never>;
// Variable: getPoetryBySlug
// Query: *[_type == "poetry" && slug.current == $slug][0]
export type GetPoetryBySlugResult = null;
// Variable: listPoetrySlug
// Query: *[_type == "poetry"] {        "slug": slug.current    }
export type ListPoetrySlugResult = Array<never>;

// Source: ./sanity/queries/readingLog.ts
// Variable: listReadingLog
// Query: *[_type == "readingLog"] | order(publishedAt desc)
export type ListReadingLogResult = Array<{
  _id: string;
  _type: "readingLog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  publishedAt: string;
  title?: string;
  author?: string;
  slug?: Slug;
  memo?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
}>;
// Variable: getReadingLogBySlug
// Query: *[_type == "readingLog" && slug.current == $slug][0]
export type GetReadingLogBySlugResult = {
  _id: string;
  _type: "readingLog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  publishedAt: string;
  title?: string;
  author?: string;
  slug?: Slug;
  memo?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
} | null;
// Variable: listReadingLogSlug
// Query: *[_type == "readingLog" && defined(slug.current)] {        "slug": slug.current    }
export type ListReadingLogSlugResult = Array<{
  slug: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n    *[_type == \"haiku\"] | order(date desc)\n  ": ListHaikuResult;
    "\n    *[_type == \"inspiration\"] | order(publishedAt desc)\n  ": ListInspirationsResult;
    "\n    *[_type == \"miscProse\"] | order(date desc)\n  ": ListMiscProseResult;
    "\n    *[_type == \"miscProse\" && slug.current == $slug][0]\n  ": GetMiscProseBySlugResult;
    "\n    *[_type == \"miscProse\"] {\n        \"slug\": slug.current\n    }\n  ": ListMiscProseSlugResult;
    "\n    *[_type == \"poetOfTheMonth\"] | order(publishedAt desc)\n  ": ListPoetOfTheMonthResult;
    "\n    *[_type == \"poetOfTheMonth\" && slug.current == $slug][0]\n  ": GetPoetOfTheMonthBySlugResult;
    "\n    *[_type == \"poetOfTheMonth\"] {\n        \"slug\": slug.current\n    }\n  ": ListPoetOfTheMonthSlugResult;
    "\n    *[_type == \"poetry\"] | order(publishedAt desc)\n  ": ListPoetryResult;
    "\n    *[_type == \"poetry\" && slug.current == $slug][0]\n  ": GetPoetryBySlugResult;
    "\n    *[_type == \"poetry\"] {\n        \"slug\": slug.current\n    }\n  ": ListPoetrySlugResult;
    "\n    *[_type == \"readingLog\"] | order(publishedAt desc)\n  ": ListReadingLogResult;
    "\n    *[_type == \"readingLog\" && slug.current == $slug][0]\n  ": GetReadingLogBySlugResult;
    "\n    *[_type == \"readingLog\" && defined(slug.current)] {\n        \"slug\": slug.current\n    }\n  ": ListReadingLogSlugResult;
  }
}
